insert into template_categories (name, slug, description, sort_order)
values
  ('Gọi điện', 'goi-dien', 'Kịch bản gọi mở đầu và khai thác nhu cầu.', 10),
  ('Tin nhắn Zalo', 'tin-nhan-zalo', 'Mẫu nhắn tin nhanh sau cuộc gọi hoặc khi chăm sóc lead.', 20),
  ('Email bán hàng', 'email-ban-hang', 'Mẫu email giới thiệu, gửi thông tin và follow-up.', 30),
  ('Follow-up', 'follow-up', 'Mẫu nhắc lại sau báo giá, demo hoặc tư vấn.', 40),
  ('Xử lý từ chối', 'xu-ly-tu-choi', 'Mẫu xử lý phản hồi thường gặp của khách.', 50),
  ('Hẹn lịch', 'hen-lich', 'Mẫu xin lịch trao đổi, demo hoặc gặp trực tiếp.', 60),
  ('Chăm sóc khách cũ', 'cham-soc-khach-cu', 'Mẫu hỏi thăm và kích hoạt lại khách cũ.', 70)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into templates (
  category_id,
  title,
  slug,
  description,
  content,
  template_type,
  situation,
  industry,
  channel,
  sort_order
)
values
((select id from template_categories where slug = 'goi-dien'), 'Kịch bản gọi mở đầu khách lạnh', 'kich-ban-goi-mo-dau-khach-lanh', 'Dùng khi gọi lần đầu cho khách chưa biết bạn.', E'Em chào anh/chị [Tên khách], em là [Tên bạn] bên [Công ty].\n\nEm có thấy bên mình đang hoạt động trong lĩnh vực [ngành/lĩnh vực], nên em gọi nhanh để xem bên mình có đang cần giải pháp về [sản phẩm/dịch vụ] không ạ.\n\nEm xin phép hỏi anh/chị 1-2 câu ngắn để xem bên em có hỗ trợ được gì cho mình không.' , 'call_script', 'Mở đầu khách lạnh', 'general', 'phone', 10),
((select id from template_categories where slug = 'goi-dien'), 'Gọi lại khách từng để lại thông tin', 'goi-lai-khach-tung-de-lai-thong-tin', 'Dùng khi khách đã từng quan tâm hoặc để lại số.', E'Em chào anh/chị [Tên khách], em là [Tên bạn] bên [Công ty].\n\nTrước đó anh/chị có để lại thông tin quan tâm đến [sản phẩm/dịch vụ]. Em gọi lại để hỏi nhanh xem nhu cầu hiện tại của mình còn phù hợp không ạ?\n\nNếu tiện, em xin phép trao đổi với anh/chị trong 2 phút.' , 'call_script', 'Gọi lại lead ấm', 'general', 'phone', 20),
((select id from template_categories where slug = 'goi-dien'), 'Mở đầu cuộc gọi theo giới thiệu', 'mo-dau-cuoc-goi-theo-gioi-thieu', 'Dùng khi bạn có người quen giới thiệu.', E'Em chào anh/chị [Tên khách], em là [Tên bạn]. Em được anh/chị [Người giới thiệu] giới thiệu liên hệ với mình.\n\nEm đang hỗ trợ các khách hàng trong lĩnh vực [ngành] xử lý vấn đề [vấn đề]. Không biết hiện tại bên mình có đang quan tâm phần này không ạ?' , 'call_script', 'Khách được giới thiệu', 'general', 'phone', 30),
((select id from template_categories where slug = 'goi-dien'), 'Khai thác nhu cầu trong cuộc gọi', 'khai-thac-nhu-cau-trong-cuoc-goi', 'Các câu hỏi ngắn để hiểu nhu cầu thật.', E'Để em tư vấn đúng hơn, em xin phép hỏi nhanh vài ý:\n\n1. Hiện tại bên mình đang xử lý [vấn đề] bằng cách nào?\n2. Điểm nào đang mất thời gian hoặc gây khó nhất?\n3. Nếu cải thiện được, anh/chị kỳ vọng kết quả như thế nào?\n4. Mình đang cần triển khai trong thời gian nào?' , 'call_script', 'Khai thác nhu cầu', 'general', 'phone', 40),
((select id from template_categories where slug = 'goi-dien'), 'Kết thúc cuộc gọi và chốt bước tiếp theo', 'ket-thuc-cuoc-goi-chot-buoc-tiep-theo', 'Dùng cuối cuộc gọi để tránh mất follow-up.', E'Em cảm ơn anh/chị đã chia sẻ. Em tóm tắt lại: bên mình đang cần [nhu cầu chính], ưu tiên [ưu tiên], và muốn xem phương án trong [thời gian].\n\nBước tiếp theo em sẽ [gửi thông tin/báo giá/hẹn demo]. Em xin phép follow-up lại vào [thời gian] để mình trao đổi tiếp nhé.' , 'call_script', 'Chốt bước tiếp theo', 'general', 'phone', 50),

((select id from template_categories where slug = 'tin-nhan-zalo'), 'Tin nhắn Zalo sau cuộc gọi đầu tiên', 'tin-nhan-zalo-sau-cuoc-goi-dau-tien', 'Gửi ngay sau khi vừa gọi xong.', E'Em chào anh/chị [Tên khách], em là [Tên bạn] vừa trao đổi với anh/chị qua điện thoại.\n\nEm gửi lại thông tin ngắn về [sản phẩm/dịch vụ] để anh/chị tiện xem lại.\n\nNếu anh/chị cần thêm thông tin hoặc muốn em tư vấn cụ thể theo nhu cầu bên mình, anh/chị nhắn em nhé.' , 'zalo_message', 'Sau cuộc gọi đầu tiên', 'general', 'zalo', 60),
((select id from template_categories where slug = 'tin-nhan-zalo'), 'Tin nhắn Zalo giới thiệu ngắn', 'tin-nhan-zalo-gioi-thieu-ngan', 'Dùng khi khách chưa tiện nghe máy.', E'Em chào anh/chị [Tên khách], em là [Tên bạn] bên [Công ty].\n\nEm liên hệ để gửi anh/chị thông tin ngắn về [sản phẩm/dịch vụ], có thể hỗ trợ bên mình [lợi ích chính].\n\nKhi nào tiện, anh/chị cho em xin 5 phút trao đổi thêm nhé.' , 'zalo_message', 'Khách chưa nghe máy', 'general', 'zalo', 70),
((select id from template_categories where slug = 'tin-nhan-zalo'), 'Zalo nhắc khách xem thông tin', 'zalo-nhac-khach-xem-thong-tin', 'Nhắc nhẹ sau khi đã gửi tài liệu.', E'Em chào anh/chị [Tên khách], em xin phép hỏi anh/chị đã có thời gian xem qua thông tin em gửi chưa ạ?\n\nNếu có điểm nào chưa rõ, em có thể giải thích nhanh hoặc gửi thêm ví dụ phù hợp với bên mình.' , 'zalo_message', 'Nhắc xem tài liệu', 'general', 'zalo', 80),
((select id from template_categories where slug = 'tin-nhan-zalo'), 'Zalo xác nhận lịch hẹn', 'zalo-xac-nhan-lich-hen', 'Xác nhận lại trước buổi hẹn.', E'Em chào anh/chị [Tên khách], em xác nhận lại lịch trao đổi của mình vào [thời gian] về nội dung [nội dung].\n\nĐến giờ hẹn em sẽ chủ động liên hệ anh/chị. Nếu cần đổi lịch, anh/chị nhắn em trước nhé.' , 'appointment', 'Xác nhận lịch', 'general', 'zalo', 90),
((select id from template_categories where slug = 'tin-nhan-zalo'), 'Zalo cảm ơn sau buổi gặp', 'zalo-cam-on-sau-buoi-gap', 'Gửi sau demo hoặc gặp trực tiếp.', E'Em cảm ơn anh/chị [Tên khách] đã dành thời gian trao đổi hôm nay.\n\nEm ghi nhận các nhu cầu chính của bên mình là [nhu cầu 1], [nhu cầu 2]. Em sẽ gửi lại tóm tắt và phương án phù hợp để anh/chị xem thêm.' , 'zalo_message', 'Sau buổi gặp', 'general', 'zalo', 100),

((select id from template_categories where slug = 'email-ban-hang'), 'Email giới thiệu giải pháp', 'email-gioi-thieu-giai-phap', 'Email đầu tiên gửi thông tin chuyên nghiệp.', E'Tiêu đề: Gửi anh/chị [Tên khách] thông tin về [sản phẩm/dịch vụ]\n\nEm chào anh/chị [Tên khách],\n\nEm là [Tên bạn] bên [Công ty]. Em gửi anh/chị thông tin ngắn về [sản phẩm/dịch vụ], giải pháp đang hỗ trợ khách hàng trong [ngành] cải thiện [lợi ích chính].\n\nNếu phù hợp, em mong có thể trao đổi với anh/chị 10-15 phút để hiểu nhu cầu bên mình và đề xuất phương án cụ thể hơn.\n\nTrân trọng,\n[Tên bạn]' , 'email', 'Giới thiệu lần đầu', 'general', 'email', 110),
((select id from template_categories where slug = 'email-ban-hang'), 'Email gửi tài liệu sau tư vấn', 'email-gui-tai-lieu-sau-tu-van', 'Gửi lại tài liệu sau cuộc gọi.', E'Tiêu đề: Tài liệu tham khảo về [sản phẩm/dịch vụ]\n\nEm chào anh/chị [Tên khách],\n\nNhư nội dung mình vừa trao đổi, em gửi anh/chị tài liệu tóm tắt về [sản phẩm/dịch vụ].\n\nCác điểm chính gồm:\n- [Lợi ích 1]\n- [Lợi ích 2]\n- [Phù hợp với nhu cầu nào]\n\nEm sẽ follow-up lại vào [thời gian] để xem anh/chị có cần thêm thông tin không ạ.' , 'email', 'Sau tư vấn', 'general', 'email', 120),
((select id from template_categories where slug = 'email-ban-hang'), 'Email mời demo', 'email-moi-demo', 'Mời khách xem demo hoặc trao đổi sâu hơn.', E'Tiêu đề: Mời anh/chị xem demo ngắn về [sản phẩm/dịch vụ]\n\nEm chào anh/chị [Tên khách],\n\nDựa trên nhu cầu anh/chị chia sẻ, em nghĩ một buổi demo 20 phút sẽ giúp mình hình dung rõ hơn cách [sản phẩm/dịch vụ] có thể hỗ trợ bên mình.\n\nAnh/chị tiện khung giờ nào trong [ngày/tuần] để em sắp xếp lịch ạ?' , 'appointment', 'Mời demo', 'general', 'email', 130),
((select id from template_categories where slug = 'email-ban-hang'), 'Email tóm tắt sau demo', 'email-tom-tat-sau-demo', 'Tổng kết nhu cầu và bước tiếp theo.', E'Tiêu đề: Tóm tắt nội dung demo hôm nay\n\nEm chào anh/chị [Tên khách],\n\nEm cảm ơn anh/chị đã dành thời gian xem demo. Em tóm tắt lại các ý chính:\n\n1. Nhu cầu hiện tại: [nhu cầu]\n2. Điểm anh/chị quan tâm: [điểm quan tâm]\n3. Bước tiếp theo: [bước tiếp theo]\n\nEm sẽ gửi [báo giá/phương án] trong thời gian sớm nhất.' , 'email', 'Sau demo', 'general', 'email', 140),

((select id from template_categories where slug = 'follow-up'), 'Follow-up sau khi gửi báo giá', 'follow-up-sau-khi-gui-bao-gia', 'Hỏi khách đã xem báo giá chưa.', E'Em chào anh/chị [Tên khách], em xin phép hỏi anh/chị đã xem qua báo giá em gửi hôm [ngày] chưa ạ?\n\nKhông biết bên mình có điểm nào cần em giải thích thêm hoặc điều chỉnh lại cho phù hợp hơn không ạ?' , 'quote_follow_up', 'Sau báo giá', 'general', 'zalo', 150),
((select id from template_categories where slug = 'follow-up'), 'Follow-up nhẹ sau 3 ngày', 'follow-up-nhe-sau-3-ngay', 'Nhắc nhẹ khi khách chưa phản hồi.', E'Em chào anh/chị [Tên khách], em nhắn lại để hỏi nhanh về nội dung [sản phẩm/dịch vụ] em gửi trước đó.\n\nKhông biết hiện tại bên mình còn quan tâm phần này không ạ, hay em nên liên hệ lại vào thời điểm khác phù hợp hơn?' , 'follow_up', 'Chưa phản hồi', 'general', 'zalo', 160),
((select id from template_categories where slug = 'follow-up'), 'Follow-up sau demo', 'follow-up-sau-demo', 'Hỏi cảm nhận sau buổi demo.', E'Em chào anh/chị [Tên khách], sau buổi demo hôm [ngày], không biết anh/chị thấy giải pháp có phù hợp với nhu cầu bên mình không ạ?\n\nNếu còn điểm nào lăn tăn, em có thể giải thích kỹ hơn hoặc gửi thêm ví dụ thực tế.' , 'follow_up', 'Sau demo', 'general', 'zalo', 170),
((select id from template_categories where slug = 'follow-up'), 'Follow-up khi khách cần hỏi sếp', 'follow-up-khi-khach-can-hoi-sep', 'Nhắc lại sau khi khách cần duyệt nội bộ.', E'Em chào anh/chị [Tên khách], em xin phép hỏi nội dung mình trao đổi hôm trước anh/chị đã tiện trao đổi lại với bên nội bộ chưa ạ?\n\nNếu cần, em có thể gửi thêm bản tóm tắt ngắn để anh/chị dễ trình bày với sếp/đội nhóm.' , 'follow_up', 'Chờ duyệt nội bộ', 'general', 'zalo', 180),
((select id from template_categories where slug = 'follow-up'), 'Follow-up chốt bước tiếp theo', 'follow-up-chot-buoc-tiep-theo', 'Dùng khi khách đã quan tâm nhưng chưa chốt.', E'Em chào anh/chị [Tên khách], để mình không bị trôi việc, em xin phép đề xuất bước tiếp theo là [bước tiếp theo].\n\nNếu anh/chị đồng ý, em sẽ [hành động cụ thể] và gửi lại cho anh/chị trong [thời gian].' , 'follow_up', 'Chốt bước tiếp theo', 'general', 'zalo', 190),

((select id from template_categories where slug = 'xu-ly-tu-choi'), 'Xử lý từ chối giá cao', 'xu-ly-tu-choi-gia-cao', 'Phản hồi khi khách nói giá cao.', E'Dạ em hiểu ý anh/chị. Về giá, bên em có thể không phải lựa chọn rẻ nhất, nhưng điểm khác biệt là [lợi ích chính 1], [lợi ích chính 2] và [cam kết/hỗ trợ].\n\nNếu mình chỉ so theo giá ban đầu thì có thể thấy cao hơn, nhưng nếu tính theo hiệu quả sử dụng và chi phí phát sinh về sau thì bên em thường tối ưu hơn cho khách hàng.' , 'objection_handling', 'Giá cao', 'general', 'phone', 200),
((select id from template_categories where slug = 'xu-ly-tu-choi'), 'Xử lý từ chối chưa có nhu cầu', 'xu-ly-tu-choi-chua-co-nhu-cau', 'Giữ cơ hội khi khách chưa cần ngay.', E'Dạ em hiểu, hiện tại bên mình chưa ưu tiên phần này.\n\nCho em hỏi thêm, thường khi nào bên mình sẽ xem xét lại nhu cầu [vấn đề/sản phẩm]? Nếu phù hợp, em xin phép lưu lại và liên hệ anh/chị vào thời điểm đó để không làm phiền mình lúc này.' , 'objection_handling', 'Chưa có nhu cầu', 'general', 'phone', 210),
((select id from template_categories where slug = 'xu-ly-tu-choi'), 'Xử lý từ chối đang dùng bên khác', 'xu-ly-tu-choi-dang-dung-ben-khac', 'Khai thác cơ hội thay thế hoặc so sánh.', E'Dạ tốt quá ạ, nghĩa là bên mình đã có giải pháp cho phần này.\n\nCho em hỏi hiện tại giải pháp đó có điểm nào anh/chị vẫn muốn cải thiện thêm không? Nếu có, em có thể gửi một phương án so sánh ngắn để anh/chị tham khảo khi cần.' , 'objection_handling', 'Đang dùng bên khác', 'general', 'phone', 220),
((select id from template_categories where slug = 'xu-ly-tu-choi'), 'Xử lý từ chối gửi thông tin trước', 'xu-ly-tu-choi-gui-thong-tin-truoc', 'Biến yêu cầu gửi thông tin thành bước tiếp theo.', E'Dạ được ạ. Để em gửi đúng thông tin, anh/chị cho em hỏi mình đang quan tâm nhất phần nào: [giá], [tính năng], [quy trình triển khai] hay [hiệu quả thực tế]?\n\nEm sẽ gửi đúng phần đó để anh/chị đỡ mất thời gian xem tài liệu quá dài.' , 'objection_handling', 'Gửi thông tin trước', 'general', 'phone', 230),
((select id from template_categories where slug = 'xu-ly-tu-choi'), 'Xử lý từ chối cần suy nghĩ thêm', 'xu-ly-tu-choi-can-suy-nghi-them', 'Xin lịch follow-up cụ thể.', E'Dạ em hiểu, quyết định này cần cân nhắc kỹ.\n\nĐể em không làm phiền nhiều lần, anh/chị cho em xin thời điểm phù hợp để hỏi lại nhé. Ví dụ [ngày/giờ], em nhắn lại ngắn gọn để xem mình đã có hướng xử lý chưa.' , 'objection_handling', 'Cần suy nghĩ', 'general', 'phone', 240),

((select id from template_categories where slug = 'hen-lich'), 'Tin nhắn hẹn lịch trao đổi lại', 'tin-nhan-hen-lich-trao-doi-lai', 'Xin 10-15 phút trao đổi sâu hơn.', E'Em chào anh/chị [Tên khách], để trao đổi kỹ hơn về nhu cầu của bên mình, anh/chị có tiện cho em xin 10-15 phút vào [thời gian đề xuất] không ạ?\n\nNếu thời gian đó chưa tiện, anh/chị cho em xin khung giờ phù hợp, em chủ động sắp xếp theo lịch của anh/chị.' , 'appointment', 'Hẹn trao đổi', 'general', 'zalo', 250),
((select id from template_categories where slug = 'hen-lich'), 'Hẹn demo sản phẩm', 'hen-demo-san-pham', 'Đề xuất demo sau khi khách quan tâm.', E'Em thấy nhu cầu của bên mình khá phù hợp để xem demo nhanh.\n\nAnh/chị có tiện 20 phút vào [thời gian] để em demo đúng phần [tính năng/quy trình] mà mình đang quan tâm không ạ?' , 'appointment', 'Hẹn demo', 'general', 'zalo', 260),
((select id from template_categories where slug = 'hen-lich'), 'Dời lịch hẹn lịch sự', 'doi-lich-hen-lich-su', 'Khi bạn cần đổi lịch với khách.', E'Em chào anh/chị [Tên khách], em xin lỗi vì lịch [thời gian cũ] có chút thay đổi.\n\nAnh/chị cho em xin phép dời sang [thời gian mới] được không ạ? Nếu chưa tiện, em sẽ theo khung giờ phù hợp của anh/chị.' , 'appointment', 'Dời lịch', 'general', 'zalo', 270),
((select id from template_categories where slug = 'hen-lich'), 'Nhắc lịch trước buổi hẹn', 'nhac-lich-truoc-buoi-hen', 'Nhắc khách trước cuộc hẹn.', E'Em chào anh/chị [Tên khách], em nhắc lại lịch trao đổi của mình vào [thời gian] hôm nay.\n\nNội dung chính là [nội dung]. Đến giờ em sẽ chủ động liên hệ anh/chị ạ.' , 'appointment', 'Nhắc lịch', 'general', 'zalo', 280),

((select id from template_categories where slug = 'cham-soc-khach-cu'), 'Hỏi thăm khách cũ sau thời gian dài', 'hoi-tham-khach-cu-sau-thoi-gian-dai', 'Kích hoạt lại khách cũ một cách tự nhiên.', E'Em chào anh/chị [Tên khách], lâu rồi em chưa có dịp hỏi thăm mình.\n\nKhông biết thời gian gần đây bên mình sử dụng [sản phẩm/dịch vụ] có ổn không ạ? Nếu có điểm nào cần hỗ trợ hoặc muốn cải thiện thêm, anh/chị cứ nhắn em nhé.' , 'follow_up', 'Hỏi thăm khách cũ', 'general', 'zalo', 290),
((select id from template_categories where slug = 'cham-soc-khach-cu'), 'Giới thiệu cập nhật mới cho khách cũ', 'gioi-thieu-cap-nhat-moi-cho-khach-cu', 'Thông báo tính năng/chính sách mới.', E'Em chào anh/chị [Tên khách], bên em vừa có cập nhật mới về [tính năng/chính sách/sản phẩm].\n\nEm nghĩ phần này có thể hữu ích với bên mình vì [lý do]. Em gửi anh/chị xem nhanh, nếu phù hợp em sẽ tư vấn thêm ạ.' , 'zalo_message', 'Cập nhật mới', 'general', 'zalo', 300),
((select id from template_categories where slug = 'cham-soc-khach-cu'), 'Xin feedback từ khách cũ', 'xin-feedback-tu-khach-cu', 'Hỏi cảm nhận để cải thiện và tìm cơ hội bán thêm.', E'Em chào anh/chị [Tên khách], em muốn hỏi nhanh cảm nhận của anh/chị sau thời gian sử dụng [sản phẩm/dịch vụ].\n\nCó điểm nào bên em đang làm tốt hoặc cần cải thiện thêm để hỗ trợ mình tốt hơn không ạ?' , 'follow_up', 'Xin feedback', 'general', 'zalo', 310),
((select id from template_categories where slug = 'cham-soc-khach-cu'), 'Gợi ý mua thêm/nâng cấp nhẹ nhàng', 'goi-y-mua-them-nang-cap-nhe-nhang', 'Dùng khi thấy khách có nhu cầu mở rộng.', E'Em chào anh/chị [Tên khách], dựa trên nhu cầu hiện tại của bên mình, em nghĩ mình có thể cân nhắc thêm [gói/tính năng/sản phẩm].\n\nPhần này giúp [lợi ích chính]. Nếu anh/chị muốn, em gửi phương án ngắn để mình tham khảo trước nhé.' , 'follow_up', 'Mua thêm/nâng cấp', 'general', 'zalo', 320),
((select id from template_categories where slug = 'cham-soc-khach-cu'), 'Mời khách cũ quay lại', 'moi-khach-cu-quay-lai', 'Kích hoạt khách đã lâu không mua.', E'Em chào anh/chị [Tên khách], em thấy mình đã lâu chưa phát sinh lại nhu cầu về [sản phẩm/dịch vụ].\n\nHiện bên em đang có [ưu đãi/cập nhật/phương án mới] khá phù hợp cho khách cũ. Anh/chị có muốn em gửi thêm thông tin để tham khảo không ạ?' , 'follow_up', 'Kích hoạt lại', 'general', 'zalo', 330)
on conflict (slug) do update
set
  category_id = excluded.category_id,
  title = excluded.title,
  description = excluded.description,
  content = excluded.content,
  template_type = excluded.template_type,
  situation = excluded.situation,
  industry = excluded.industry,
  channel = excluded.channel,
  sort_order = excluded.sort_order,
  is_public = true,
  is_active = true,
  updated_at = now();
